In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('log2.csv')
data.head()

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
0        57222                53            54587                    53   
1        56258              3389            56258                  3389   
2         6881             50321            43265                 50321   
3        50553              3389            50553                  3389   
4        50002               443            45848                   443   

  Action  Bytes  Bytes Sent  Bytes Received  Packets  Elapsed Time (sec)  \
0  allow    177          94              83        2                  30   
1  allow   4768        1600            3168       19                  17   
2  allow    238         118             120        2                1199   
3  allow   3327        1438            1889       15                  17   
4  allow  25358        6778           18580       31                  16   

   pkts_sent  pkts_received  
0          1              1  
1         10              9  
2          1              1  
3          8              7  
4         13             18

In [4]:
x=data.drop('Action',axis=1)
y=pd.DataFrame(data['Action'])

In [7]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=1)

In [9]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)

C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [13]:
from sklearn.metrics import classification_report,confusion_matrix

In [11]:
rfc_pred = rfc.predict(X_test)

In [14]:
print(confusion_matrix(y_test,rfc_pred))

[[15019     7     0     0]
 [    1  5998    15     0]
 [    0    12  5143     0]
 [    0    10     0     8]]


In [15]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

       allow       1.00      1.00      1.00     15026
        deny       1.00      1.00      1.00      6014
        drop       1.00      1.00      1.00      5155
  reset-both       1.00      0.44      0.62        18

    accuracy                           1.00     26213
   macro avg       1.00      0.86      0.90     26213
weighted avg       1.00      1.00      1.00     26213

